[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
ffi = true
auto_detect_solc = false
solc_version = '0.8.20'
optimizer_runs = 5_000
optimizer = true

fs_permissions = [
    { access = "read-write", path = "./"}
]

remappings = [
    '@safe-global/safe-core-protocol=lib/safe-core-protocol',
    '@openzeppelin/=lib/openzeppelin-contracts'
]

[rpc_endpoints]
localhost="http://127.0.0.1:8545"
goerli="https://ethereum-goerli.publicnode.com"
sepolia="https://ethereum-sepolia.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
