hashed_message = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nullifierHash = ""
proposal_id = ""
return = ""
root = ""
